# Generated by Django 2.2.5 on 2019-09-24 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNormal',
            fields=[
                ('class_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('type_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnCard',
            fields=[
                ('column_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=10)),
                ('column_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=10)),
                ('class_type', models.ManyToManyField(to='automatic_card.ClassType')),
            ],
        ),
        migrations.CreateModel(
            name='RowCard',
            fields=[
                ('row_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('row_name', models.CharField(max_length=10)),
                ('row_index', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('semester_year', models.IntegerField()),
                ('semester_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('group_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=10)),
                ('teacher_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Grade')),
                ('teacher_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.TeacherGroup')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClassNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.IntegerField()),
                ('class_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ClassNormal')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='class_normal',
            field=models.ManyToManyField(through='automatic_card.SubjectClassNormal', to='automatic_card.ClassNormal'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='automatic_card.Teacher'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=10)),
                ('class_normal', models.ManyToManyField(to='automatic_card.ClassNormal')),
                ('column_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ColumnCard')),
                ('row_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.RowCard')),
                ('teacher', models.ManyToManyField(to='automatic_card.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='rowcard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Semester'),
        ),
        migrations.AddField(
            model_name='columncard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Semester'),
        ),
        migrations.AddField(
            model_name='classnormal',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Grade'),
        ),
        migrations.AddField(
            model_name='classnormal',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ClassType'),
        ),
        migrations.AddField(
            model_name='classnormal',
            name='teacher',
            field=models.ManyToManyField(to='automatic_card.Teacher'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('class_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ClassNormal')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ColumnCard')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.RowCard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Teacher')),
            ],
        ),
    ]
