# Generated by Django 2.2.5 on 2019-09-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNormalRule',
            fields=[
                ('rule_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=10)),
                ('class_normal', models.ManyToManyField(to='automatic_card.ClassNormal')),
                ('column_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ColumnCard')),
                ('row_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.RowCard')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRule',
            fields=[
                ('rule_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=10)),
                ('column_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.ColumnCard')),
                ('row_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.RowCard')),
                ('teacher', models.ManyToManyField(to='automatic_card.Teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
