# Generated by Django 2.2.5 on 2019-09-26 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_card', '0003_graderule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnormal',
            name='head_master',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_master_id', to='automatic_card.Teacher'),
        ),
    ]
