# Generated by Django 2.2.5 on 2019-09-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_card', '0004_classnormal_head_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Subject')),
            ],
        ),
    ]
