# Generated by Django 2.2.5 on 2019-09-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_card', '0006_auto_20190929_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automatic_card.Teacher'),
        ),
    ]
